.\" Process this file with
.\" groff -man -Tascii itgmania.6
.\"
.TH itgmania 6 "JUNE 2023" Linux "User Manuals"
.SH NAME
itgmania \- Advanced cross-platform rhythm game for home and arcade use
.SH SYNOPSIS
.B itgmania
.SH DESCRIPTION
This package was specifically built for the Raspberry Pi platform.
For more information about the process used to create this package,
visit https://github.com/itgmania/raspios-itgmania-deb

There is much more that must be configured on a Raspberry Pi to
make ITGMania playable. For more information, instructions,
& a set of scripts to do it all automatically, visit
https://github.com/itgmania/raspios-itgmania-build
.SH AUTHOR
Packaged by ITGMania Developers <itgmania@gmail.com> 